stages:
  - setup
  - validation
  - analyze_sample_apps

# The pipeline covers a series of triggers to ensure full testing and coverage

# Debug Stage
debug_merge_request:
  stage: setup
  script:
    - echo "Pipeline Source $CI_PIPELINE_SOURCE"
    - echo "Commit Branch (Source) $CI_COMMIT_REF_NAME"
    - echo "Target Branch (Merge Request) $CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - echo "Source Branch Name (Merge Request) $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
    - echo "Merge ID environment variable (Merge Request) $CI_MERGE_REQUEST_IID"

# Validate Conditional Triggers
validation_trigger:
  stage: validation
  trigger:
    include: tools/pipelines/child-ci-setup-validation.yml
  rules:
    # Condition 1: Branch is not main, qa, or development
    - if: '$CI_COMMIT_REF_NAME != "main" && $CI_COMMIT_REF_NAME != "qa" && $CI_COMMIT_REF_NAME != "development"'
      when: always

    # Condition 2: Triggered by a push event
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always

    # Condition 3: Triggered by a merge request event (source branch is not "development")
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME != "development"'
      when: always

    # Condition 4: Triggered by a merge request event (source branch is "development", "qa", or "main")
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "development" || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "qa" || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "main"'
      when: always

    # Fallback: Skip if no condition matches
    - when: never

    
# Analyze Conditional Triggers
analyze_flutter_mobile:
  stage: analyze_sample_apps
  trigger:
    include: tools/pipelines/child-ci-analyze-flutter-mobile.yml
  needs:
    - job: validation_trigger
  rules:
    # Always runs after validation trigger
    - when: always

# Release Triggers
gitlab_github_release:
  stage: release
  trigger:
    include: tools/pipelines/backend/child-ci-release.yml
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: always
#  stage: triggers
#  trigger:
#    include: tools/pipelines/child-ci-qa.yml
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "qa" || $CI_COMMIT_BRANCH == "qa"

#conditional_preprod:
#  stage: triggers
#  trigger:
#    include: tools/pipelines/child-ci-preprod.yml
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "preprod" || $CI_COMMIT_BRANCH == "preprod"

#conditional_production:
#  stage: triggers
#  trigger:
#    include: tools/pipelines/child-ci-production.yml
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "production" || $CI_COMMIT_BRANCH == "production"