name: okta_identity_dart_auth_sdk
description: A Dart SDK for Okta Authentication, enabling secure server-side authentication and user management for Dart-based backend applications.
version: 0.0.1-pre
repository: https://github.com/aortem_sdks/okta_identity_dart_auth_sdk

environment:
  sdk: ^3.6.0

# Add regular dependencies here.

dependencies:
#------------------ STANDARD FEATURES---------------------------------
## There are three standard libraries.  Each one can be used with a different xxx 

  ds_standard_features: ^0.0.3 #Standard Dart Team Utilities For HTTP //Default
  build_web_compilers: ^4.0.11
  jwt_generator: ^0.0.3
  cryptography: ^2.7.0


#------------------ TESTING FEATURES---------------------------------

dev_dependencies:
  ds_tools_testing: ^0.0.1-pre+2 #Standard Dart Team Testing Tools
  test_reporter: any #required to generate JUnit report 
  http: any
  git_hooks: any

# Optional Local Hooks for development.
git_hooks:
  hooks:
    pre-commit: ./local_dev_tools/validate_commit.dart
    commit-msg: ./local_dev_tools/validate_commit_msg.dart
    pre-push: ./local_dev_tools/validate_branch.dart